version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - gomodguard_v2
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused
    - nlreturn
    - bodyclose
    - gocheckcompilerdirectives
    - errname
    - errchkjson
  settings:
    nlreturn:
      block-size: 3
    staticcheck:
      checks:
        - all
        - -ST1003 # struct field ... should be ... (mostly acronyms such as Http -> HTTP)
    gomodguard_v2:
      allowed:
        - module: github.com/cenkalti/backoff/v4
        - module: github.com/Khan/genqlient
        - module: github.com/google/go-querystring
        - module: github.com/PuerkitoBio/rehttp
        - module: github.com/superfly/client-signals/go
        - module: github.com/superfly/graphql
        - module: github.com/superfly/macaroon
        - module: github.com/superfly/macaroon/flyio
        - module: github.com/superfly/macaroon/tp
        - module: golang.org/.*
          match-type: regex
        - module: go.opentelemetry.io/.*
          match-type: regex
      blocked:
        - module: github.com/superfly/flyctl
          reason: "`api` can not depend on flyctl project because it pulls tons of dependencies"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      module-path: github.com/superfly/flyctl
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
