version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - gomodguard
    - govet
    - ineffassign
    - staticcheck
    - unconvert
    - unused
  settings:
    staticcheck:
      checks:
        - all
        - -ST1003 # struct field ... should be ... (mostly acronyms such as Http -> HTTP)
        - -ST1005 # error strings should not be capitalized
        - -ST1016 # methods on the same type should have the same receiver name
        - -QF1001 # could apply De Morgan's law
        - -QF1002 # could use tagged switch
        - -QF1008 # could remove embedded field ... from selector
    gomodguard:
      allowed:
        modules:
          - github.com/cenkalti/backoff/v4
          - github.com/Khan/genqlient
          - github.com/google/go-querystring
          - github.com/PuerkitoBio/rehttp
          - github.com/superfly/graphql
          - github.com/superfly/macaroon
          - github.com/superfly/macaroon/flyio
          - github.com/superfly/macaroon/tp
        domains:
          - golang.org
          - go.opentelemetry.io
      blocked:
        modules:
          - github.com/superfly/flyctl:
              reason: '`api` can not depend on flyctl project because it pulls tons of dependencies'
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    gofumpt:
      module-path: github.com/superfly/flyctl
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
