// Code generated by "stringer -type=SecretType"; DO NOT EDIT.

package fly

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AppSecret-1]
	_ = x[VolumeEncryptionKey-2]
	_ = x[SECRET_TYPE_KMS_HS256-3]
	_ = x[SECRET_TYPE_KMS_HS384-4]
	_ = x[SECRET_TYPE_KMS_HS512-5]
	_ = x[SECRET_TYPE_KMS_XAES256GCM-6]
	_ = x[SECRET_TYPE_KMS_NACL_AUTH-7]
	_ = x[SECRET_TYPE_KMS_NACL_BOX-8]
	_ = x[SECRET_TYPE_KMS_NACL_SECRETBOX-9]
	_ = x[SECRET_TYPE_KMS_NACL_SIGN-10]
}

const _SecretType_name = "AppSecretVolumeEncryptionKeySECRET_TYPE_KMS_HS256SECRET_TYPE_KMS_HS384SECRET_TYPE_KMS_HS512SECRET_TYPE_KMS_XAES256GCMSECRET_TYPE_KMS_NACL_AUTHSECRET_TYPE_KMS_NACL_BOXSECRET_TYPE_KMS_NACL_SECRETBOXSECRET_TYPE_KMS_NACL_SIGN"

var _SecretType_index = [...]uint8{0, 9, 28, 49, 70, 91, 117, 142, 166, 196, 221}

func (i SecretType) String() string {
	i -= 1
	if i < 0 || i >= SecretType(len(_SecretType_index)-1) {
		return "SecretType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SecretType_name[_SecretType_index[i]:_SecretType_index[i+1]]
}
