package flaps

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"
)

var ErrFlapsNotFound = &FlapsError{ResponseStatusCode: http.StatusNotFound}

// ErrFlapsGone is returned when the API reports a resource as gone (HTTP 410).
// Managed Postgres returns it for a cluster that has already been deleted.
var ErrFlapsGone = &FlapsError{ResponseStatusCode: http.StatusGone}

type StatusCode string

const (
	unknown                 StatusCode = "unknown"
	regionOOCapacity        StatusCode = "insufficient_capacity"
	volumePlacementCapacity StatusCode = "volume_placement_capacity"
	nameTaken               StatusCode = "name_taken"
)

type errorResponse struct {
	Error      string     `json:"error"`
	StatusCode StatusCode `json:"status"`
}

type FlapsError struct {
	OriginalError      error
	ResponseStatusCode int
	ResponseBody       []byte
	FlyRequestId       string
	TraceID            string
}

func (fe *FlapsError) Error() string {
	if fe.OriginalError == nil {
		return ""
	}

	return fe.OriginalError.Error()
}

func (fe *FlapsError) Suggestion() string {
	statusCode := fe.StatusCode()
	if statusCode == nil {
		return ""
	}

	switch *statusCode {
	case unknown:
		return ""
	case regionOOCapacity:
		// TODO(billy): once we have support for 'backup regions', suggest creating adding those (or eveven better, just do it automatically)
		return "Try choosing a different region for machine creation"
	case volumePlacementCapacity:
		return "The host holding this machine's volume is out of resources. Fork the volume to place it on another host."
	case nameTaken:
		// Worth spelling out: the API says the name is taken, and the caller
		// looks at their own organization, sees no such app, and concludes the
		// error is wrong. App names are one global namespace, so the app
		// holding the name is usually one they cannot see.
		return "App names are unique across all of Fly.io, not just your organization, so this name may be held by an app you cannot see. Try a different name."
	}

	return ""
}

type ErrorStatusCode interface {
	error
	StatusCode() *StatusCode
}

func GetErrorStatusCode(err error) *StatusCode {
	var ferr ErrorStatusCode
	if errors.As(err, &ferr) {
		return ferr.StatusCode()
	}

	return nil
}

// TODO: we might not actually need an interface type here
type ErrorRequestID interface {
	ErrRequestID() string
}

func GetErrorRequestID(err error) string {
	var ferr ErrorRequestID
	if errors.As(err, &ferr) {
		return ferr.ErrRequestID()
	}

	return ""
}

type ErrorTraceID interface {
	ErrTraceID() string
}

func GetErrorTraceID(err error) string {
	var ferr ErrorTraceID
	if errors.As(err, &ferr) {
		return ferr.ErrTraceID()
	}

	return ""
}

func (fe *FlapsError) StatusCode() *StatusCode {
	var errResp errorResponse
	unmarshalErr := json.Unmarshal(fe.ResponseBody, &errResp)

	if unmarshalErr != nil {
		return nil
	}

	return &errResp.StatusCode
}

func (fe *FlapsError) ErrRequestID() string {
	return fe.FlyRequestId
}

func (fe *FlapsError) ErrTraceID() string {
	return fe.TraceID
}

func (fe *FlapsError) Is(target error) bool {
	if other, ok := target.(*FlapsError); ok {
		return fe.ResponseStatusCode == other.ResponseStatusCode
	}

	return false
}

func (fe *FlapsError) Unwrap() error {
	return fe.OriginalError
}

func (fe *FlapsError) ResponseBodyString() string {
	return string(fe.ResponseBody)
}

// legacyNameTakenMessage is the prose an app-name collision produced before
// the name_taken status code existed.
//
// It is generated by the API's validation layer rather than written down as
// part of the API, which is the whole reason matching it is a poor contract
// and the status code exists. The API still sends it alongside the code, so
// this stays useful as a fallback.
const legacyNameTakenMessage = "Name has already been taken"

// IsNameTakenError reports whether err is a rejection of an app name that is
// already in use.
//
// Prefer this over matching the error's text: it reads the status code the API
// sets, and falls back to the message only when there is no code at all. The
// fallback covers two cases and is not vestigial:
//
//   - a client running against a Fly.io API that predates the status code, and
//   - app creation that never went through the Machines API at all, such as the
//     extension providers that create their apps over GraphQL, where nothing
//     sets a status code in the first place.
//
// Note what the fallback deliberately does not match: a collision that races
// past the validation and trips the database constraint instead is reported
// with a generic message covering every unique constraint the platform has,
// not just app names. Telling that one apart needs context only the server
// has, so the API classifies it there and reports it here as the name_taken
// code.
func IsNameTakenError(err error) bool {
	if err == nil {
		return false
	}

	// A status code, whatever it says, means the API classified this failure.
	// Take it at its word: reaching for the message after that can only
	// misclassify, and an error that aggregates or wraps another one can
	// easily carry the legacy text without being a name collision.
	if code := GetErrorStatusCode(err); code != nil && *code != "" {
		return *code == nameTaken
	}

	return strings.Contains(err.Error(), legacyNameTakenMessage)
}

// CapacityScope says which pool of resources a Machines API call ran out
// of. A caller decides what to do from the scope alone: a host-scoped
// failure is fixed by placing the machine somewhere else, a region-scoped
// one is not fixable by the caller at all.
type CapacityScope int

const (
	// CapacityScopeNone means the error is not a capacity failure.
	CapacityScopeNone CapacityScope = iota

	// CapacityScopeHost means the host the machine already lives on
	// cannot fit the requested guest. Produced by machine update, which
	// can only re-reserve resources on the current host. Recreating the
	// machine lets the placer pick another host.
	CapacityScopeHost

	// CapacityScopeVolumePlacement means the machine must be created on
	// the host holding one of its volumes, and that host cannot fit the
	// guest. Only the volume's host is exhausted; the region may have room.
	CapacityScopeVolumePlacement

	// CapacityScopeRegion means no host in the region can place the
	// machine or volume. Retrying, relocating, or recreating in the same
	// region will not help.
	CapacityScopeRegion
)

func (s CapacityScope) String() string {
	switch s {
	case CapacityScopeHost:
		return "host"
	case CapacityScopeVolumePlacement:
		return "volume_placement"
	case CapacityScopeRegion:
		return "region"
	default:
		return "none"
	}
}

func IsCapacityError(err error) bool {
	return CapacityScopeOf(err) != CapacityScopeNone
}

func CapacityScopeOf(err error) CapacityScope {
	var ferr *FlapsError
	if !errors.As(err, &ferr) {
		return CapacityScopeNone
	}

	if code := ferr.StatusCode(); code != nil && *code != "" {
		switch *code {
		case regionOOCapacity:
			return CapacityScopeRegion
		case volumePlacementCapacity:
			return CapacityScopeVolumePlacement
		default:
			return CapacityScopeNone
		}
	}

	if ferr.ResponseStatusCode != http.StatusConflict {
		return CapacityScopeNone
	}

	return hostCapacityScopeFromText(ferr.responseErrorText())
}

// flydResourcePhrases are the messages flyd's resource managers attach to
// a reservation that cannot be satisfied. They reach the client inside a 409 body,
// sometimes wrapped as "could not reserve resource for machine: <phrase> on the
// current host" by flyd. This is not an API contract, which is why this is a
// fallback.
var flydResourcePhrases = []string{
	"insufficient CPUs available to fulfill request",
	"insufficient memory available to fulfill request",
	"insufficient IPs available to fulfill request",
	// NOTE:
	// This one only appears on the create path after flaps already tried
	// every host, so one can say it's region scoped. Here we classify it
	// as host though, because a client can try again and hit a proper 422
	// insufficient_capacity if the problem is /not/ a host failure.
	"insufficient resources available to fulfill request",
}

// flydNoCapacityPhrase is what flaps returns when every candidate host
// refused a volume create or fork ("aborted: no capacity"). It is the
// only 409 that means the whole region, not one host.
const flydNoCapacityPhrase = "no capacity"

func hostCapacityScopeFromText(text string) CapacityScope {
	for _, phrase := range flydResourcePhrases {
		if strings.Contains(text, phrase) {
			return CapacityScopeHost
		}
	}

	if strings.HasSuffix(strings.TrimSpace(text), flydNoCapacityPhrase) {
		return CapacityScopeRegion
	}

	return CapacityScopeNone
}

func (fe *FlapsError) responseErrorText() string {
	var errResp errorResponse
	if json.Unmarshal(fe.ResponseBody, &errResp) == nil && errResp.Error != "" {
		return errResp.Error
	}

	return string(fe.ResponseBody)
}
