// Code generated by "stringer -type=flapsAction"; DO NOT EDIT.

package flaps

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[none-0]
	_ = x[appCreate-1]
	_ = x[appGet-2]
	_ = x[machineLaunch-3]
	_ = x[machineUpdate-4]
	_ = x[machineStart-5]
	_ = x[machineWait-6]
	_ = x[machineStop-7]
	_ = x[machineRestart-8]
	_ = x[machineGet-9]
	_ = x[machineList-10]
	_ = x[machineDestroy-11]
	_ = x[machineKill-12]
	_ = x[machineFindLease-13]
	_ = x[machineAcquireLease-14]
	_ = x[machineRefreshLease-15]
	_ = x[machineReleaseLease-16]
	_ = x[machineExec-17]
	_ = x[machinePs-18]
	_ = x[machineCordon-19]
	_ = x[machineUncordon-20]
	_ = x[machineSuspend-21]
	_ = x[appSecretsList-22]
	_ = x[appSecretGet-23]
	_ = x[appSecretSet-24]
	_ = x[appSecretDelete-25]
	_ = x[appSecretUpdate-26]
	_ = x[secretkeysList-27]
	_ = x[secretkeyGet-28]
	_ = x[secretkeySet-29]
	_ = x[secretkeyGenerate-30]
	_ = x[secretkeyDelete-31]
	_ = x[secretkeyEncrypt-32]
	_ = x[secretkeyDecrypt-33]
	_ = x[secretkeySign-34]
	_ = x[secretkeyVerify-35]
	_ = x[volumeList-36]
	_ = x[volumeCreate-37]
	_ = x[volumetUpdate-38]
	_ = x[volumeGet-39]
	_ = x[volumeSnapshotCreate-40]
	_ = x[volumeSnapshotList-41]
	_ = x[volumeExtend-42]
	_ = x[volumeDelete-43]
	_ = x[metadataSet-44]
	_ = x[metadataGet-45]
	_ = x[metadataDel-46]
	_ = x[regionsGet-47]
	_ = x[placementPost-48]
}

const _flapsAction_name = "noneappCreateappGetmachineLaunchmachineUpdatemachineStartmachineWaitmachineStopmachineRestartmachineGetmachineListmachineDestroymachineKillmachineFindLeasemachineAcquireLeasemachineRefreshLeasemachineReleaseLeasemachineExecmachinePsmachineCordonmachineUncordonmachineSuspendappSecretsListappSecretGetappSecretSetappSecretDeleteappSecretUpdatesecretkeysListsecretkeyGetsecretkeySetsecretkeyGeneratesecretkeyDeletesecretkeyEncryptsecretkeyDecryptsecretkeySignsecretkeyVerifyvolumeListvolumeCreatevolumetUpdatevolumeGetvolumeSnapshotCreatevolumeSnapshotListvolumeExtendvolumeDeletemetadataSetmetadataGetmetadataDelregionsGetplacementPost"

var _flapsAction_index = [...]uint16{0, 4, 13, 19, 32, 45, 57, 68, 79, 93, 103, 114, 128, 139, 155, 174, 193, 212, 223, 232, 245, 260, 274, 288, 300, 312, 327, 342, 356, 368, 380, 397, 412, 428, 444, 457, 472, 482, 494, 507, 516, 536, 554, 566, 578, 589, 600, 611, 621, 634}

func (i flapsAction) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_flapsAction_index)-1 {
		return "flapsAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _flapsAction_name[_flapsAction_index[idx]:_flapsAction_index[idx+1]]
}
