package flaps

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"
)

var ErrFlapsNotFound = &FlapsError{ResponseStatusCode: http.StatusNotFound}

type StatusCode string

const (
	unknown          StatusCode = "unknown"
	regionOOCapacity StatusCode = "insufficient_capacity"
	nameTaken        StatusCode = "name_taken"
)

type errorResponse struct {
	Error      string     `json:"error"`
	StatusCode StatusCode `json:"status"`
}

type FlapsError struct {
	OriginalError      error
	ResponseStatusCode int
	ResponseBody       []byte
	FlyRequestId       string
	TraceID            string
}

func (fe *FlapsError) Error() string {
	if fe.OriginalError == nil {
		return ""
	}

	return fe.OriginalError.Error()
}

func (fe *FlapsError) Suggestion() string {
	statusCode := fe.StatusCode()
	if statusCode == nil {
		return ""
	}

	switch *statusCode {
	case unknown:
		return ""
	case regionOOCapacity:
		// TODO(billy): once we have support for 'backup regions', suggest creating adding those (or eveven better, just do it automatically)
		return "Try choosing a different region for machine creation"
	case nameTaken:
		// Worth spelling out: the API says the name is taken, and the caller
		// looks at their own organization, sees no such app, and concludes the
		// error is wrong. App names are one global namespace, so the app
		// holding the name is usually one they cannot see.
		return "App names are unique across all of Fly.io, not just your organization, so this name may be held by an app you cannot see. Try a different name."
	}

	return ""
}

type ErrorStatusCode interface {
	error
	StatusCode() *StatusCode
}

func GetErrorStatusCode(err error) *StatusCode {
	var ferr ErrorStatusCode
	if errors.As(err, &ferr) {
		return ferr.StatusCode()
	}

	return nil
}

// TODO: we might not actually need an interface type here
type ErrorRequestID interface {
	ErrRequestID() string
}

func GetErrorRequestID(err error) string {
	var ferr ErrorRequestID
	if errors.As(err, &ferr) {
		return ferr.ErrRequestID()
	}

	return ""
}

type ErrorTraceID interface {
	ErrTraceID() string
}

func GetErrorTraceID(err error) string {
	var ferr ErrorTraceID
	if errors.As(err, &ferr) {
		return ferr.ErrTraceID()
	}

	return ""
}

func (fe *FlapsError) StatusCode() *StatusCode {
	var errResp errorResponse
	unmarshalErr := json.Unmarshal(fe.ResponseBody, &errResp)

	if unmarshalErr != nil {
		return nil
	}

	return &errResp.StatusCode
}

func (fe *FlapsError) ErrRequestID() string {
	return fe.FlyRequestId
}

func (fe *FlapsError) ErrTraceID() string {
	return fe.TraceID
}

func (fe *FlapsError) Is(target error) bool {
	if other, ok := target.(*FlapsError); ok {
		return fe.ResponseStatusCode == other.ResponseStatusCode
	}

	return false
}

func (fe *FlapsError) Unwrap() error {
	return fe.OriginalError
}

func (fe *FlapsError) ResponseBodyString() string {
	return string(fe.ResponseBody)
}

// legacyNameTakenMessage is the prose an app-name collision produced before
// the name_taken status code existed.
//
// It is generated by the API's validation layer rather than written down as
// part of the API, which is the whole reason matching it is a poor contract
// and the status code exists. The API still sends it alongside the code, so
// this stays useful as a fallback.
const legacyNameTakenMessage = "Name has already been taken"

// IsNameTakenError reports whether err is a rejection of an app name that is
// already in use.
//
// Prefer this over matching the error's text: it reads the name_taken status
// code the API sets, and only falls back to the message when there is no code
// to read. The fallback covers two cases and is not vestigial:
//
//   - a client running against a Fly.io API that predates the status code, and
//   - app creation that never went through the Machines API at all, such as the
//     extension providers that create their apps over GraphQL, where nothing
//     sets a status code in the first place.
//
// Note what the fallback deliberately does not match: a collision that races
// past the validation and trips the database constraint instead is reported
// with a generic message covering every unique constraint the platform has,
// not just app names. Telling that one apart needs context only the server
// has, so the API classifies it there and reports it here as the name_taken
// code.
func IsNameTakenError(err error) bool {
	if err == nil {
		return false
	}

	if code := GetErrorStatusCode(err); code != nil && *code == nameTaken {
		return true
	}

	return strings.Contains(err.Error(), legacyNameTakenMessage)
}
