// Code generated by "stringer -type=flapsAction"; DO NOT EDIT.

package flaps

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[none-0]
	_ = x[appCreate-1]
	_ = x[machineLaunch-2]
	_ = x[machineUpdate-3]
	_ = x[machineStart-4]
	_ = x[machineWait-5]
	_ = x[machineStop-6]
	_ = x[machineRestart-7]
	_ = x[machineGet-8]
	_ = x[machineList-9]
	_ = x[machineDestroy-10]
	_ = x[machineKill-11]
	_ = x[machineFindLease-12]
	_ = x[machineAcquireLease-13]
	_ = x[machineRefreshLease-14]
	_ = x[machineReleaseLease-15]
	_ = x[machineExec-16]
	_ = x[machinePs-17]
	_ = x[machineCordon-18]
	_ = x[machineUncordon-19]
	_ = x[machineSuspend-20]
	_ = x[appSecretsList-21]
	_ = x[appSecretGet-22]
	_ = x[appSecretSet-23]
	_ = x[appSecretDelete-24]
	_ = x[secretkeysList-25]
	_ = x[secretkeyGet-26]
	_ = x[secretkeySet-27]
	_ = x[secretkeyGenerate-28]
	_ = x[secretkeyDelete-29]
	_ = x[secretkeyEncrypt-30]
	_ = x[secretkeyDecrypt-31]
	_ = x[secretkeySign-32]
	_ = x[secretkeyVerify-33]
	_ = x[volumeList-34]
	_ = x[volumeCreate-35]
	_ = x[volumetUpdate-36]
	_ = x[volumeGet-37]
	_ = x[volumeSnapshotCreate-38]
	_ = x[volumeSnapshotList-39]
	_ = x[volumeExtend-40]
	_ = x[volumeDelete-41]
	_ = x[metadataSet-42]
	_ = x[metadataGet-43]
	_ = x[metadataDel-44]
	_ = x[regionsGet-45]
	_ = x[placementPost-46]
	_ = x[ipAssignmentsList-47]
	_ = x[ipAssignmentCreate-48]
	_ = x[ipAssignmentDelete-49]
}

const _flapsAction_name = "noneappCreatemachineLaunchmachineUpdatemachineStartmachineWaitmachineStopmachineRestartmachineGetmachineListmachineDestroymachineKillmachineFindLeasemachineAcquireLeasemachineRefreshLeasemachineReleaseLeasemachineExecmachinePsmachineCordonmachineUncordonmachineSuspendappSecretsListappSecretGetappSecretSetappSecretDeletesecretkeysListsecretkeyGetsecretkeySetsecretkeyGeneratesecretkeyDeletesecretkeyEncryptsecretkeyDecryptsecretkeySignsecretkeyVerifyvolumeListvolumeCreatevolumetUpdatevolumeGetvolumeSnapshotCreatevolumeSnapshotListvolumeExtendvolumeDeletemetadataSetmetadataGetmetadataDelregionsGetplacementPostipAssignmentsListipAssignmentCreateipAssignmentDelete"

var _flapsAction_index = [...]uint16{0, 4, 13, 26, 39, 51, 62, 73, 87, 97, 108, 122, 133, 149, 168, 187, 206, 217, 226, 239, 254, 268, 282, 294, 306, 321, 335, 347, 359, 376, 391, 407, 423, 436, 451, 461, 473, 486, 495, 515, 533, 545, 557, 568, 579, 590, 600, 613, 630, 648, 666}

func (i flapsAction) String() string {
	if i < 0 || i >= flapsAction(len(_flapsAction_index)-1) {
		return "flapsAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _flapsAction_name[_flapsAction_index[i]:_flapsAction_index[i+1]]
}
